### ISSUE TITLE
Following instructions in README.md with lakefile.lean results in error

### ISSUE THREAD

**Issue by ndcroos** [leanprover-community/import-graph#19]
Following the instructions in the Usage section in the README.md, I get the following, I get the following error when running `lake update -R importGraph`:
```
info: downloading component 'lean'
info: installing component 'lean'
info: [root]: lakefile.lean and lakefile.toml are both present; using lakefile.lean
error: .\.\lakefile.lean:1:0: error: unexpected identifier; expected command
error: .\.\lakefile.lean: package configuration has errors
```

**Comment by ndcroos** [comment]
Hi @joneugster, thanks for getting back to me. I did use the `con-nf` project to run the instructions. I created a new lakefile.lean with `require importGraph from git "https://github.com/leanprover-community/import-graph" @ "main"`/. I did  run `lake update -R importGraph` in `con-nf`, with the error as result.

**Comment by joneugster** [comment]
I updated the README with a section about `lakefile.toml` as well as about `mathlib`: https://github.com/leanprover-community/import-graph/commit/bff0cabecd585e7b5bf3675d41471171191242de

I actually didn't read your error messages before, so my guess is that you had both a `lakefile.toml` and `lakefile.lean` present. If you still have problems, please reopen the issue with a link to the "`con-nf` project", I'm afraid I don't know what that is.
